# Generated by Django 4.0.7 on 2023-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'ADMIN'), ('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], max_length=15),
        ),
    ]
