# Generated by Django 4.0.7 on 2023-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
