<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-07-06 20:10

=======
# Generated by Django 4.0.7 on 2023-07-06 17:08

from django.conf import settings
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cart_products', '0002_initial'),
        ('products', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_products', '0002_initial'),
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
<<<<<<< HEAD
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
=======
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
        ),
    ]
