# Generated by Django 4.0.7 on 2023-06-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_alter_cart_options_alter_cart_id_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'placed'), ('PROGRESS', 'progress'), ('DELIVERED', 'delivered')], max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carts', models.ManyToManyField(related_name='orders', to='carts.cart')),
            ],
        ),
    ]
