<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-07-06 20:10

from django.conf import settings
=======
# Generated by Django 4.0.7 on 2023-07-06 17:08

>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('products', '0001_initial'),
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
<<<<<<< HEAD
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
=======
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='products.product'),
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14
        ),
    ]
