# Generated by Django 4.0.7 on 2023-06-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options_alter_cart_id_alter_cart_user'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
    ]
