# Generated by Django 4.0.7 on 2023-07-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_products', '0001_initial'),
        ('orders', '0003_remove_order_carts_order_cart_product_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_order', to='cart_products.cartproduct'),
        ),
    ]
