# Generated by Django 4.0.7 on 2023-07-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_product',
        ),
    ]
