# Generated by Django 4.0.7 on 2023-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_product',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
