<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-07-06 20:10
=======
# Generated by Django 4.0.7 on 2023-07-06 17:08
>>>>>>> 0a977f0d4da1c1afec677e702d050aadbe132f14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
